name: CD dotnet
on:
  push:
    branches:
      - main
env:
    REPO_NAME: wbf-backend
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push .NET Docker Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${REPO_NAME}:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.actor }}/${REPO_NAME}:latest
