name: CI dotnet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.406'

      - name: Restore Dependencies
        run: dotnet restore 

      - name: Build Project
        run: dotnet build

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
